### ISSUE TITLE
Artwork scanners should be able to support TV & Movie

### ISSUE THREAD

**Issue by Omertron** [YAMJ/yamj-v3#170]
Both TheMovieDb and FanartTV have artwork for TV shows and Movies.

There needs to be a way to pass in the type of the video that we are looking for artwork for so that they can appropriately process the video.

Using the IMoviePosterScanner, IMovieFanartScanner, etc, interfaces is not always sufficient

Example: Searching for a Title and Year could apply to TV and Movies.

**Comment by modmax** [comment]
Yes .. that's correct.

In intended to rewrite the artwork interfaces, so that only a movie, series, season or person may be passed to it.
The rest should be done by the underlying scanner implementation. The scanner then knows exactly what kind of poster/fanart is needed. Perhaps he may call the same methods to gather the poster and fanarts inside the scanner ... but that is invisible to the rest of the application, which doesn't care from where the scanner gets his informations.
