### ISSUE TITLE
"api/video/episodes?seasonid" with dataitem "files" returns no records, w/o "files" works fine

### ISSUE THREAD

**Issue by Diodato** [YAMJ/yamj-v3#171]
"api/video/episodes?seasonid=xx&dataitems=artwork,outline,plot" returns records
"api/video/episodes?seasonid=xx&dataitems=artwork,outline,plot,files" returns 0

**Comment by jluc2808** [comment]
when i'm using 
api/video/episodes.json?&seriesid=5&seasonid=22&dataitems=plot,files,rating
i have no problem 

i tried 
api/video/episodes.json?&seriesid=5&seasonid=22&dataitems=artwork,outline,plot,files

be carefull the seasonid isn't enough , you need to specify the seriesid , because you could have the same seasonid in several series

**Comment by Diodato** [comment]
Closing. Was using an old version.
