### ISSUE TITLE
API to propagate the update of artwork 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#220]
#188 and  #198 allow to update video and person 
the updated status is performed for metadata and is not propagated to artworks (egal for api/file/update)

2 solutions (which are complementary) 
add to the API : api/rescan/artwork/{video=video_Id}&{artwork_type}
add an argument api/rescan/movie/{id}&propagate={artwork_type}
with artwork_type = fanart, poster, banner, all
egal for /yamj3/api/file/update/{stage_fileId}&propagate={video, artwork_type}

**Comment by modmax** [comment]
Normally it's not necessary to scan for new artworks, just because the video data will be rescanned; that are independent jobs and done by different scanners.

The only case if which a rescan should be forced is the case, when a movie database id is changed or removed. In that case the "old" artworks should be marked as deleted (and later on deleted via a deletion task) and the artworks should be set to UPDATED to force a rescan with the new ID's.
This is part of #219.

If an artwork stage file is updated, then the "local artwork" may have been changed; if changed (dterminedby timestamp), then the local artwork will be queued for creationg new images.

From my point of view there's nothing to do here anymore.

**Comment by jluc2808** [comment]
for some reason , i can't tell all the resaon (fail to finish the job , site unavailable when processing, server ko, stoping job , ....) , , some artwork are with status , notfound, error, 
in the skin this have the result to display dummy and sometime nothing , then at this time it will be perfect if the user could ask api to rescan (set staus to updated) , so perhaps the propagate request have no reality , the rescan one is needed 

could you add api/rescan/artwork/{video=video_id}&type=videotype&artwork=artworktype

**Comment by modmax** [comment]
The API calls are ready and most of the data will be dropped, if the external id of a source is changed or removed.

Following API calls are present
* /api/video/{movie,series,season,episode/updateexternalid?id=&sourcedb=&externalid=
* /api/video/{movie,series,season,episode/removexternalid?id=&sourcedb=
* /api/person/updateexternalid?id=&sourcedb=&externalid=
* /api/preson/removexternalid?id=&sourcedb=

Still TODO:
Remove instance variables of movie/series/season/episode/person itself, when scanned from a removed source.

**Comment by modmax** [comment]
Following methods for rescannig artworks are available:

/api/rescan/movie/artwork/{id}
/api/rescan/series/artwork/{id}
/api/rescan/season/artwork/{id}
/api/rescan/episode/artwork/{id}
/api/rescan/person/artwork/{id}
/api/rescan/boxset/artwork/{id}

where id is the ID of the movie/series/season/...
