### ISSUE TITLE
still a problem why updating person 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#261]
i have a person already scanned with status DONE and filmography_status DONE
michael BACHAL
the external_id available are in this order : 
allocine: 67966
imdb: nm0045209
tmdb: 58744

when i call the API to fill all field fot this person , biography is emply (field is null in the db person) 

when i look at allocine it's empty 
at this step everything is OK 

now i want to update the person , because biography is not empty in imdb site 

so i start api/rescan/person/5887
no biography update

i try to disable allocine reference (as there is a bug - my previous issue) but without sucess 

so i delete via API allocine source , the rescan which is immedialty done , begin with allocine , so no biography update 

i thought that the sequence should we be able to store the 1rst available item (biography) , rather the 1rst one ? or how to proceed to get the update of imdb without changing all the parameters ?

**Comment by modmax** [comment]
1.) A scan will only fail if there is a scraping error; otherwise any value is just "not present".
Onl in cases where the first scan fails (i.e. person not found or connection error), then the next scanner will be used.

2.) Have you set
yamj3.sourcedb.scanner.person.alternate.always=true
in your configuration?
Only in that cases the secondary scanners will be used for the person. 
Also each scan starts with the precedence you have given to the onöince scannes via static configuration.

The sources can correctly be skipped with the latest snapshot .. so I cannot see any problems.

**Comment by jluc2808** [comment]
to answser : 
1)  no error , just no value for biography
2) yes the settings is  :yamj3.sourcedb.scanner.person.alternate.always=true

so the last try is : 
3) i update for the last release where you have twikked to store the html mini bio if the API biography for imdb is empty , disable allociné site for that person , rescan and now the biography is filled
