### ISSUE TITLE
Api index/video sorted by Year doesn't give the same results each time 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#275]
when i'm using 
api/index/video.json?type=movie,series&sortby=videoYear&sortdir=DESC&dataitems=status,boxset,rating,videosource&artwork=poster&watched=all

i don't get the same results everytime 
1rst time the 1rst movie is 

    "results": [
        {
            "id": 586,
            "title": "Kingsman : Services secrets",
            "originalTitle": "Kingsman: The Secret Service",

2nd time with the same api order 
"results": [
        {
            "id": 605,
            "title": "Vice Versa",
            "originalTitle": "Inside Out",
            "watched": true,

3rd time 
    "results": [
        {
            "id": 586,
            "title": "Kingsman : Services secrets",

etc....

**Comment by modmax** [comment]
The problem is the sorting; if you just sort by year, then the year sorting will work.
But if you have several movies with the same year, what is expected then? Which sort should be done in that case? By ID oder creation_time or name?

Unless no second sorting criteria (in addition to year) is given, the result my vary due database issues which just guarantees, that the year is sorted, but nothin is sorted within the "group" of year.

**Comment by jluc2808** [comment]
could we add a second criteria in the sortby order ?

**Comment by modmax** [comment]
Right now: NO
Reason: sortby and sortdir are concatenated, so that sortby=X and sortdir=DESC will turned into sql equivalent: ORDER BY X DESC. If you leave out sortdir in an API request, then ASC will be appended by the current implementation.

I would recommend to drop the sortdir parameter and therefore set "sortby" option to be a string array, such like "year DESC,id", so that this string can be applied as order by.

But this will influence several API call (which is at least each api call with a given sortby and/or sortdir).

**Comment by jluc2808** [comment]
i agree with the proposal , unify into the sortby any sorting will simplify all mecanism 
for compatibility with what is already implemented in api , i suggest the following rules 

if no sortdir item :  don't add anything 
if ASC or DESC is specified in sortby order:  take the ASC, or DESC given in the sortby order in the sql order 
if ASC or DESC is specified in sortby order and in sortdir order :  don't add any sortdir value even if specified , just take the ASC, or DESC given in the sortby order in the sql order 
if sortdir item is asked: add the rules asked at the end of the sql request

**Comment by modmax** [comment]
Is used the described behaviour.

**Comment by jluc2808** [comment]
tested ok
