### ISSUE TITLE
wrong externalId for series with tmdb 

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#294]
the series_ids for tmdb value are wrong 
ex: the walking dead series have for series_ids value : 153021

if i'm looking at the tmdb site with 
https://www.themoviedb.org/tv/153021  i get a Oops!—We can't find the page you're looking for

the real value is 
https://www.themoviedb.org/tv/1402

**Comment by modmax** [comment]
Have you set an NFO or anything else with sets the correct id?
Or an ID tag inside the file names?
In any other case it can occur, that the series or movie is not
detected correctly ... cause the detection is based on filename (name and year)
and can lead to false movie/series detection.

This is something which cannot be fixed, cause it depends on the input data
and what the TMDb api detects for it.

But you always have the possibility to reset the external id of TMDb in order
to scan the correct series.

**Comment by jluc2808** [comment]
i have no NFO , i have checked  and the series_ids value is the tvdb one , not the tmdb , so 2 reasons
- either tmdb redirect on tvdb site to find the right id 
- either the sourcedb value is the not the correct one

**Comment by jluc2808** [comment]
this is available if tvdb is setted on season_ids
if no season_ids is stored then the series_ids is wrong 

ex: 

game of thrones
series_ids : 121361  sourcedb: tmdb 
season_ids: 121361 sourcedb: tvdb

**Comment by modmax** [comment]
Ah okay ... I will take a look into the plugins ... perhaps there is a problem with setting the ID's.

**Comment by modmax** [comment]
There was an error in the TVDb plugin, so that every time the series id for TVDB should be set, it was with the ID of TMDB ... just a minor misspelling problem which lead to that error.

Please download and use the newest tvdb plugin 3.0.1 which should be available in a few minutes on the mediaplayersite. Also delete all series ID with with source tmdb in the database. Therefore you can use following sql statements.

`update series ser set ser.status='UPDATED' where ser.status='DONE' and exists (select 1 from series_ids ids where ids.sourcedb='tmdb' and ids.series_id=ser.id);`
`delete from series_ids where sourcedb='tmdb';`

**Comment by jluc2808** [comment]
tested ok
