### ISSUE TITLE
Reduce time to access to the skins index files

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#318]
Hello,

Another feature which could be interesting would be to render easily access to the skin index file.
When using eversion, we have to browse core/resources/skins/yamj3_eversion and select the eversion.phf file.
It could be interesting to organize differently the skins folder (skins folder at the same level than core and filescanner package for example) or provide a way to access to the skin file easily.
It will help users to earn time and render easily the yamj launch.

**Comment by jluc2808** [comment]
you don't need to install the eversion_yamj3 under core/resources , you are able to install (unzip) anywhere you want , even on an network_share like a NAS/PC on an USB drive or local drive

**Comment by dav1170** [comment]
Hello Jluc2808,

So perhaps it could be interesting to review where is installed the skins when we install them from the web interface (It was my case): eversion skin as been installed in the core/resources/skins folder by default.

Note: if you have any info about how install skins in another folder, it would be very helpfull.

regards

**Comment by jluc2808** [comment]
i don't now how it could be more simple , you could unzip eversion_yamj3 where you want , just unzip the eversion_yamj3 distribution 

of course if you install from bikini , it will be stored  under resources/skins because it's the place for skins 
but as i specify in the eversion_yamj3 thread you could unzip where you want
