### ISSUE TITLE
Some files are still marked as unwatched even if there is a watched file

### ISSUE THREAD

**Issue by dav1170** [YAMJ/yamj-v3#329]
Hello,

I was wondering why some files are still marked as watched even if I've setted a watched file.

`ls -la  /foo/bar/films/Foo.*`

> -rwxr-xr-x 1 user group 111111 Sep 11  2012  /foo/bar/films/Foo.fanart.jpg
-rwxr-xr-x 1 user group      22384 Sep 21  2012  /foo/bar/films/Foo.jpg
-rwxr-xr-x 1 user group 222222222 May 18  2008  /foo/bar/films/Foo.mkv
-rwxr-xr-x 1 user group          0 Dec  6  2014  /foo/bar/films/Foo.mkv.watched
-rwxr-xr-x 1 user group       1943 Mar 16  2014  /foo/bar/filmsFoo.nfo

filescanner display no exception and we can show that file has been viewed:

> [11.08.2017 19:42:56] INFO  org.yamj.filescanner.ScannerManagementImpl  - Scanning file 'Foo.mkv.watched'

jetty instance seems not displaying any exception.

but file is still displayed in the unwatched category of eversion.

Here's a part of the returned output of the SQL query on this videodata in db:

>  publication_year: 2013
     quote: NULL
     release_country_code: NULL
     release_date: NULL
    kip_scan_api: NULL
     skip_scan_nfo: NULL
     tagline: NULL
      top_rank: -1
     trailer_last_scanned: NULL
        trailer_status: NEW
    watched:
     watched_api:
    watched_api_last_date: NULL
     watched_date: NULL
     watched_nfo:
    watched_nfo_last_date: NULL
   watched_trakttv:
watched_trakttv_last_date: NULL
  season_id: NULL

Regards

**Comment by jluc2808** [comment]
the watched directory is specified in the yamj3-core-static properties, only watched file inside this folder are scanned and stored as a valid watch file, there is other mecanism that could set the watch status like traktv, or set watch by bikini or set by programs , both are stored in the db and are computed by eversion.

the storage of your watched file seems to be everytime with the movie, if all the movies are inside the same folder, set this folder as the watched folder to scan, rescan and that will do the trick, otherwise copy all your watched inside a unique folder and rescan after you modified the watch folder parameter and a restart of jetty
