### ISSUE TITLE
add language selector in config and API

### ISSUE THREAD

**Issue by jluc2808** [YAMJ/yamj-v3#82]
it would be great if the language selector could be stored in the yamjv3 parameters , like prefered_skin_language and could be edited with yamjv3 web config editor and fetched with an API request. 

take care of the 2 parts 
- info which are stored in the database, 
- info which are used by the skin , 
both need to be independant.
French people would have french label and english contents
like "synopsis" (french label for plot): and english plot

**Comment by modmax** [comment]
Is this still needed?
The language can be passed with every API call in order to fetch some values (countries and languages) in the localized version.
If you have multiple skins, then ONE setting for skin_language will not fit, cause the YAMJ3 core does not know teh skins ... and shouldn't know them.

**Comment by jluc2808** [comment]
as exposed in the issue don't think it's already needed,
